management:
  endpoint:
    health:
      show-details: always
  server:
    servlet:
      context-path: /actuator
spring:
  application:
    name: data-receive-core-server
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true

